name: Daily AI Code Generator

on:
  schedule:
    - cron: '0 5 * * *'   # Runs every day at 2 AM UTC
  workflow_dispatch:        # Allow manual runs too

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install google-generativeai python-dotenv

      - name: Run AI Code Generator
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python generate_code.py

      - name: Commit and push generated code
        run: |
          git config user.name "latifurrafi"
          git config user.email "latifurrafi@gmail.com"
          git add .
          git commit -m "🤖code $(date '+%Y-%m-%d')" || echo "No new changes to commit"
          git push
